---
name: Copy and push to BLVD Insights
on:
  push:
    branches:
      - "main"
    paths:
      - "deep-learning.ipynb"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copy new deep-learning.ipynb
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN_GRANTHAM }}
        src_path: /deep-learning.ipynb
        src_branch: main
        dst_path: /content/deep-learning.ipynb
        dst_owner: boulevardcg
        dst_repo_name: insights_portal
        dst_branch: autoupdate-content
        commit_message: Updates to deep-learning.ipynb   